version: '3'
services:
  web:
    build: .
    container_name: behave
    ports:
     - "5000:5000"
    volumes:
      - "./:/usr/src/app"

  database:
    image: postgres:11-alpine
    container_name: behave_pgsql
    ports:
      - "5430:5432"
    environment:
      POSTGRES_PASSWORD: pythonlab
      POSTGRES_USER: pythonlab
      POSTGRES_DB: pythonlab
      POSTGRES_VOLUME: ../.postgresql